### ISSUE TITLE
model redundancies  

### ISSUE THREAD

**Issue by ailymas** [codergogoi/nodejs_microservice#2]
redefining Product model in Order model instead of getting it with api ?

**Comment by codergogoi** [comment]
It does not matter for orders.  Because we need the purchase history of the product. It should not be supposed to change the product information once ordered. You can keep minimum viable product information in the order model as well. If we use the latest updated product reference with the help of API  / RPC / State Function call then the customer will get the wrong product information that is updated by Vendor (eg: Price, supplier or some other information that may change and required to claim). But again it's an MPV to educate people about the microservice ecosystem. Feel free to implement as you like.

Cheers!
